package conexion_y_funciones;
// Generated 12/02/2022 10:43:28 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * CiudadSede generated by hbm2java
 */
public class CiudadSede  implements java.io.Serializable {


     private int idCiudad;
     private String departamento;
     private String ciudad;
     private Set sedeses = new HashSet(0);
     private Set destinatarios = new HashSet(0);
     private Set clientes = new HashSet(0);

    public CiudadSede() {
    }

	
    public CiudadSede(int idCiudad, String departamento, String ciudad) {
        this.idCiudad = idCiudad;
        this.departamento = departamento;
        this.ciudad = ciudad;
    }
    public CiudadSede(int idCiudad, String departamento, String ciudad, Set sedeses, Set destinatarios, Set clientes) {
       this.idCiudad = idCiudad;
       this.departamento = departamento;
       this.ciudad = ciudad;
       this.sedeses = sedeses;
       this.destinatarios = destinatarios;
       this.clientes = clientes;
    }
   
    public int getIdCiudad() {
        return this.idCiudad;
    }
    
    public void setIdCiudad(int idCiudad) {
        this.idCiudad = idCiudad;
    }
    public String getDepartamento() {
        return this.departamento;
    }
    
    public void setDepartamento(String departamento) {
        this.departamento = departamento;
    }
    public String getCiudad() {
        return this.ciudad;
    }
    
    public void setCiudad(String ciudad) {
        this.ciudad = ciudad;
    }
    public Set getSedeses() {
        return this.sedeses;
    }
    
    public void setSedeses(Set sedeses) {
        this.sedeses = sedeses;
    }
    public Set getDestinatarios() {
        return this.destinatarios;
    }
    
    public void setDestinatarios(Set destinatarios) {
        this.destinatarios = destinatarios;
    }
    public Set getClientes() {
        return this.clientes;
    }
    
    public void setClientes(Set clientes) {
        this.clientes = clientes;
    }




}


