package conexion_y_funciones;
// Generated 12/02/2022 10:43:28 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * EstadoEmpleado generated by hbm2java
 */
public class EstadoEmpleado  implements java.io.Serializable {


     private int idEstado;
     private String tipoEstado;
     private Set informacionEmpleadoses = new HashSet(0);

    public EstadoEmpleado() {
    }

	
    public EstadoEmpleado(int idEstado, String tipoEstado) {
        this.idEstado = idEstado;
        this.tipoEstado = tipoEstado;
    }
    public EstadoEmpleado(int idEstado, String tipoEstado, Set informacionEmpleadoses) {
       this.idEstado = idEstado;
       this.tipoEstado = tipoEstado;
       this.informacionEmpleadoses = informacionEmpleadoses;
    }
   
    public int getIdEstado() {
        return this.idEstado;
    }
    
    public void setIdEstado(int idEstado) {
        this.idEstado = idEstado;
    }
    public String getTipoEstado() {
        return this.tipoEstado;
    }
    
    public void setTipoEstado(String tipoEstado) {
        this.tipoEstado = tipoEstado;
    }
    public Set getInformacionEmpleadoses() {
        return this.informacionEmpleadoses;
    }
    
    public void setInformacionEmpleadoses(Set informacionEmpleadoses) {
        this.informacionEmpleadoses = informacionEmpleadoses;
    }




}


