package conexion_y_funciones;
// Generated 12/02/2022 10:43:28 PM by Hibernate Tools 4.3.1



/**
 * PermisosRol generated by hbm2java
 */
public class PermisosRol  implements java.io.Serializable {


     private int idPermisoRol;
     private RolEmpleados rolEmpleados;
     private int terminalVentas;
     private int crearUsuario;
     private int editarUsuario;
     private int eliminarUsuario;
     private int crearSede;
     private int consultarSede;
     private Integer eliminarSede;

    public PermisosRol() {
    }

	
    public PermisosRol(int idPermisoRol, RolEmpleados rolEmpleados, int terminalVentas, int crearUsuario, int editarUsuario, int eliminarUsuario, int crearSede, int consultarSede) {
        this.idPermisoRol = idPermisoRol;
        this.rolEmpleados = rolEmpleados;
        this.terminalVentas = terminalVentas;
        this.crearUsuario = crearUsuario;
        this.editarUsuario = editarUsuario;
        this.eliminarUsuario = eliminarUsuario;
        this.crearSede = crearSede;
        this.consultarSede = consultarSede;
    }
    public PermisosRol(int idPermisoRol, RolEmpleados rolEmpleados, int terminalVentas, int crearUsuario, int editarUsuario, int eliminarUsuario, int crearSede, int consultarSede, Integer eliminarSede) {
       this.idPermisoRol = idPermisoRol;
       this.rolEmpleados = rolEmpleados;
       this.terminalVentas = terminalVentas;
       this.crearUsuario = crearUsuario;
       this.editarUsuario = editarUsuario;
       this.eliminarUsuario = eliminarUsuario;
       this.crearSede = crearSede;
       this.consultarSede = consultarSede;
       this.eliminarSede = eliminarSede;
    }
   
    public int getIdPermisoRol() {
        return this.idPermisoRol;
    }
    
    public void setIdPermisoRol(int idPermisoRol) {
        this.idPermisoRol = idPermisoRol;
    }
    public RolEmpleados getRolEmpleados() {
        return this.rolEmpleados;
    }
    
    public void setRolEmpleados(RolEmpleados rolEmpleados) {
        this.rolEmpleados = rolEmpleados;
    }
    public int getTerminalVentas() {
        return this.terminalVentas;
    }
    
    public void setTerminalVentas(int terminalVentas) {
        this.terminalVentas = terminalVentas;
    }
    public int getCrearUsuario() {
        return this.crearUsuario;
    }
    
    public void setCrearUsuario(int crearUsuario) {
        this.crearUsuario = crearUsuario;
    }
    public int getEditarUsuario() {
        return this.editarUsuario;
    }
    
    public void setEditarUsuario(int editarUsuario) {
        this.editarUsuario = editarUsuario;
    }
    public int getEliminarUsuario() {
        return this.eliminarUsuario;
    }
    
    public void setEliminarUsuario(int eliminarUsuario) {
        this.eliminarUsuario = eliminarUsuario;
    }
    public int getCrearSede() {
        return this.crearSede;
    }
    
    public void setCrearSede(int crearSede) {
        this.crearSede = crearSede;
    }
    public int getConsultarSede() {
        return this.consultarSede;
    }
    
    public void setConsultarSede(int consultarSede) {
        this.consultarSede = consultarSede;
    }
    public Integer getEliminarSede() {
        return this.eliminarSede;
    }
    
    public void setEliminarSede(Integer eliminarSede) {
        this.eliminarSede = eliminarSede;
    }




}


