package conexion_y_funciones;
// Generated 26/01/2022 11:28:34 PM by Hibernate Tools 4.3.1



/**
 * PrecioEnvios generated by hbm2java
 */
public class PrecioEnvios  implements java.io.Serializable {


     private int idPrecioEnvio;

    public PrecioEnvios() {
    }

    public PrecioEnvios(int idPrecioEnvio) {
       this.idPrecioEnvio = idPrecioEnvio;
    }
   
    public int getIdPrecioEnvio() {
        return this.idPrecioEnvio;
    }
    
    public void setIdPrecioEnvio(int idPrecioEnvio) {
        this.idPrecioEnvio = idPrecioEnvio;
    }




}


