package conexion_y_funciones;
// Generated 26/01/2022 11:28:34 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * RolEmpleados generated by hbm2java
 */
public class RolEmpleados  implements java.io.Serializable {


     private int idTipoEmpleado;
     private String tipoEmpleado;
     private Set informacionEmpleadoses = new HashSet(0);

    public RolEmpleados() {
    }

	
    public RolEmpleados(int idTipoEmpleado, String tipoEmpleado) {
        this.idTipoEmpleado = idTipoEmpleado;
        this.tipoEmpleado = tipoEmpleado;
    }
    public RolEmpleados(int idTipoEmpleado, String tipoEmpleado, Set informacionEmpleadoses) {
       this.idTipoEmpleado = idTipoEmpleado;
       this.tipoEmpleado = tipoEmpleado;
       this.informacionEmpleadoses = informacionEmpleadoses;
    }
   
    public int getIdTipoEmpleado() {
        return this.idTipoEmpleado;
    }
    
    public void setIdTipoEmpleado(int idTipoEmpleado) {
        this.idTipoEmpleado = idTipoEmpleado;
    }
    public String getTipoEmpleado() {
        return this.tipoEmpleado;
    }
    
    public void setTipoEmpleado(String tipoEmpleado) {
        this.tipoEmpleado = tipoEmpleado;
    }
    public Set getInformacionEmpleadoses() {
        return this.informacionEmpleadoses;
    }
    
    public void setInformacionEmpleadoses(Set informacionEmpleadoses) {
        this.informacionEmpleadoses = informacionEmpleadoses;
    }




}


