package conexion_y_funciones;
// Generated 12/02/2022 10:43:28 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Sedes generated by hbm2java
 */
public class Sedes  implements java.io.Serializable {


     private int idSede;
     private CiudadSede ciudadSede;
     private String barrio;
     private String direccion;
     private Set telefonosSedeses = new HashSet(0);
     private Set informacionEmpleadoses = new HashSet(0);
     private Set facturases = new HashSet(0);

    public Sedes() {
    }

	
    public Sedes(int idSede, CiudadSede ciudadSede, String barrio, String direccion) {
        this.idSede = idSede;
        this.ciudadSede = ciudadSede;
        this.barrio = barrio;
        this.direccion = direccion;
    }
    public Sedes(int idSede, CiudadSede ciudadSede, String barrio, String direccion, Set telefonosSedeses, Set informacionEmpleadoses, Set facturases) {
       this.idSede = idSede;
       this.ciudadSede = ciudadSede;
       this.barrio = barrio;
       this.direccion = direccion;
       this.telefonosSedeses = telefonosSedeses;
       this.informacionEmpleadoses = informacionEmpleadoses;
       this.facturases = facturases;
    }
   
    public int getIdSede() {
        return this.idSede;
    }
    
    public void setIdSede(int idSede) {
        this.idSede = idSede;
    }
    public CiudadSede getCiudadSede() {
        return this.ciudadSede;
    }
    
    public void setCiudadSede(CiudadSede ciudadSede) {
        this.ciudadSede = ciudadSede;
    }
    public String getBarrio() {
        return this.barrio;
    }
    
    public void setBarrio(String barrio) {
        this.barrio = barrio;
    }
    public String getDireccion() {
        return this.direccion;
    }
    
    public void setDireccion(String direccion) {
        this.direccion = direccion;
    }
    public Set getTelefonosSedeses() {
        return this.telefonosSedeses;
    }
    
    public void setTelefonosSedeses(Set telefonosSedeses) {
        this.telefonosSedeses = telefonosSedeses;
    }
    public Set getInformacionEmpleadoses() {
        return this.informacionEmpleadoses;
    }
    
    public void setInformacionEmpleadoses(Set informacionEmpleadoses) {
        this.informacionEmpleadoses = informacionEmpleadoses;
    }
    public Set getFacturases() {
        return this.facturases;
    }
    
    public void setFacturases(Set facturases) {
        this.facturases = facturases;
    }




}


