package conexion_y_funciones;
// Generated 12/02/2022 10:43:28 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Seguro generated by hbm2java
 */
public class Seguro  implements java.io.Serializable {


     private int idSeguro;
     private String tipoSeguro;
     private int valorSeguro;
     private String descripcion;
     private Set envioses = new HashSet(0);

    public Seguro() {
    }

	
    public Seguro(int idSeguro, String tipoSeguro, int valorSeguro, String descripcion) {
        this.idSeguro = idSeguro;
        this.tipoSeguro = tipoSeguro;
        this.valorSeguro = valorSeguro;
        this.descripcion = descripcion;
    }
    public Seguro(int idSeguro, String tipoSeguro, int valorSeguro, String descripcion, Set envioses) {
       this.idSeguro = idSeguro;
       this.tipoSeguro = tipoSeguro;
       this.valorSeguro = valorSeguro;
       this.descripcion = descripcion;
       this.envioses = envioses;
    }
   
    public int getIdSeguro() {
        return this.idSeguro;
    }
    
    public void setIdSeguro(int idSeguro) {
        this.idSeguro = idSeguro;
    }
    public String getTipoSeguro() {
        return this.tipoSeguro;
    }
    
    public void setTipoSeguro(String tipoSeguro) {
        this.tipoSeguro = tipoSeguro;
    }
    public int getValorSeguro() {
        return this.valorSeguro;
    }
    
    public void setValorSeguro(int valorSeguro) {
        this.valorSeguro = valorSeguro;
    }
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }
    public Set getEnvioses() {
        return this.envioses;
    }
    
    public void setEnvioses(Set envioses) {
        this.envioses = envioses;
    }




}


