package conexion_y_funciones;
// Generated 12/02/2022 10:43:28 PM by Hibernate Tools 4.3.1



/**
 * TelefonosSedes generated by hbm2java
 */
public class TelefonosSedes  implements java.io.Serializable {


     private TelefonosSedesId id;
     private Sedes sedes;

    public TelefonosSedes() {
    }

    public TelefonosSedes(TelefonosSedesId id, Sedes sedes) {
       this.id = id;
       this.sedes = sedes;
    }
   
    public TelefonosSedesId getId() {
        return this.id;
    }
    
    public void setId(TelefonosSedesId id) {
        this.id = id;
    }
    public Sedes getSedes() {
        return this.sedes;
    }
    
    public void setSedes(Sedes sedes) {
        this.sedes = sedes;
    }




}


