package conexion_y_funciones;
// Generated 12/02/2022 10:43:28 PM by Hibernate Tools 4.3.1



/**
 * TelefonosSedesId generated by hbm2java
 */
public class TelefonosSedesId  implements java.io.Serializable {


     private int idSede;
     private String telefono;

    public TelefonosSedesId() {
    }

    public TelefonosSedesId(int idSede, String telefono) {
       this.idSede = idSede;
       this.telefono = telefono;
    }
   
    public int getIdSede() {
        return this.idSede;
    }
    
    public void setIdSede(int idSede) {
        this.idSede = idSede;
    }
    public String getTelefono() {
        return this.telefono;
    }
    
    public void setTelefono(String telefono) {
        this.telefono = telefono;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof TelefonosSedesId) ) return false;
		 TelefonosSedesId castOther = ( TelefonosSedesId ) other; 
         
		 return (this.getIdSede()==castOther.getIdSede())
 && ( (this.getTelefono()==castOther.getTelefono()) || ( this.getTelefono()!=null && castOther.getTelefono()!=null && this.getTelefono().equals(castOther.getTelefono()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + this.getIdSede();
         result = 37 * result + ( getTelefono() == null ? 0 : this.getTelefono().hashCode() );
         return result;
   }   


}


