package conexion_y_funciones;
// Generated 12/02/2022 10:43:28 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * TipoPago generated by hbm2java
 */
public class TipoPago  implements java.io.Serializable {


     private int idTipoPago;
     private String tipoPago;
     private Set facturases = new HashSet(0);

    public TipoPago() {
    }

	
    public TipoPago(int idTipoPago, String tipoPago) {
        this.idTipoPago = idTipoPago;
        this.tipoPago = tipoPago;
    }
    public TipoPago(int idTipoPago, String tipoPago, Set facturases) {
       this.idTipoPago = idTipoPago;
       this.tipoPago = tipoPago;
       this.facturases = facturases;
    }
   
    public int getIdTipoPago() {
        return this.idTipoPago;
    }
    
    public void setIdTipoPago(int idTipoPago) {
        this.idTipoPago = idTipoPago;
    }
    public String getTipoPago() {
        return this.tipoPago;
    }
    
    public void setTipoPago(String tipoPago) {
        this.tipoPago = tipoPago;
    }
    public Set getFacturases() {
        return this.facturases;
    }
    
    public void setFacturases(Set facturases) {
        this.facturases = facturases;
    }




}


